Bug fix

diff --git a/.github/workflows/ci_pr_validation.yml b/.github/workflows/ci_pr_validation.yml
--- a/.github/workflows/ci_pr_validation.yml
+++ b/.github/workflows/ci_pr_validation.yml
@@ -58,3 +58,16 @@ jobs:
                 fi
 
                 ctest --preset=$TEST_PRESET
+
+    pr_verification_summary:
+        needs: verify_pr
+        runs-on: ubuntu-latest
+        if: always() # Run even if some matrix jobs failed.
+        steps:
+            - name: Check if all jobs succeeded
+              run: |
+                if [[ "${{ needs.verify_pr.result }}" != "success" ]]; then
+                  echo "One or more jobs failed"
+                  exit 1
+                fi
+                echo "All jobs completed successfully"
